"""full_schema

Revision ID: c73000f499f2
Revises: 0001
Create Date: 2026-05-19 15:03:12.040015

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector  # noqa: F401  — referenced by VECTOR column type
import app.utils.encryption  # noqa: F401  — referenced by EncryptedString column type

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Named enums that this migration creates and must explicitly drop in downgrade()
# (autogenerate doesn't emit DROP TYPE statements).
_ENUMS_TO_DROP = (
    "document_classification",
    "document_status",
    "urgency_level",
    "referral_status",
    "discharge_status",
    "urgency_tier",
    "task_type",
    "task_status",
    "task_priority",
    "prior_auth_status",
    "prior_auth_event_type",
    "verification_status",
    "eligibility_result",
    "appointment_status",
    "outreach_channel",
    "outreach_status",
    "call_type",
    "call_status",
    "fax_direction",
    "fax_type",
    "fax_status",
    "workflow_status",
    "invocation_type",
    "eval_type",
)


def upgrade() -> None:
    # pgvector is required for the `payer_rules.embedding` column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payer_rules",
        sa.Column("payer_name", sa.String(length=128), nullable=False),
        sa.Column("payer_id", sa.String(length=64), nullable=True),
        sa.Column("procedure_code", sa.String(length=16), nullable=False),
        sa.Column("procedure_name", sa.String(length=255), nullable=True),
        sa.Column("auth_required", sa.Boolean(), nullable=False),
        sa.Column("required_documents", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("typical_turnaround_days", sa.Integer(), nullable=True),
        sa.Column("guidelines_text", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payer_rules_payer_name"), "payer_rules", ["payer_name"], unique=False)
    op.create_index(
        op.f("ix_payer_rules_procedure_code"), "payer_rules", ["procedure_code"], unique=False
    )
    op.create_table(
        "eval_runs",
        sa.Column(
            "eval_type",
            sa.Enum("extraction", "retrieval", "voice", "workflow", name="eval_type"),
            nullable=False,
        ),
        sa.Column("test_set_version", sa.String(length=64), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("num_samples", sa.Integer(), nullable=False),
        sa.Column("run_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("run_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_eval_runs_clinic_id"), "eval_runs", ["clinic_id"], unique=False)
    op.create_index(op.f("ix_eval_runs_eval_type"), "eval_runs", ["eval_type"], unique=False)
    op.create_table(
        "workflow_runs",
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", "retrying", name="workflow_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "input_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "output_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_runs_clinic_id"), "workflow_runs", ["clinic_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_runs_task_name"), "workflow_runs", ["task_name"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "referral",
                "discharge_summary",
                "lab",
                "imaging",
                "other",
                "unclassified",
                name="document_classification",
            ),
            nullable=False,
        ),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "classifying",
                "classified",
                "extracting",
                "extracted",
                "needs_review",
                "reviewed",
                "processed",
                "error",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "urgency",
            sa.Enum("stat", "urgent", "routine", "unclassified", name="urgency_level"),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("source_fax_number", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_clinic_id"), "documents", ["clinic_id"], unique=False)
    op.create_table(
        "insurance_policies",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("payer_name", sa.String(length=128), nullable=False),
        sa.Column("payer_id", sa.String(length=64), nullable=True),
        sa.Column("member_id", app.utils.encryption.EncryptedString(), nullable=False),
        sa.Column("group_number", sa.String(length=64), nullable=True),
        sa.Column("plan_type", sa.String(length=64), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("unverified", "verified", "invalid", "expired", name="verification_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_insurance_policies_clinic_id"), "insurance_policies", ["clinic_id"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_policies_patient_id"), "insurance_policies", ["patient_id"], unique=False
    )
    op.create_table(
        "ai_invocations",
        sa.Column(
            "invocation_type",
            sa.Enum(
                "classification",
                "extraction",
                "auth_check",
                "voice_dialogue",
                "appeal_generation",
                "other",
                name="invocation_type",
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("input_summary", sa.Text(), nullable=True),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column(
            "confidence_scores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_invocations_clinic_id"), "ai_invocations", ["clinic_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_invocations_invocation_type"),
        "ai_invocations",
        ["invocation_type"],
        unique=False,
    )
    op.create_table(
        "discharge_summaries",
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("referring_provider_id", sa.UUID(), nullable=True),
        sa.Column("discharge_date", sa.Date(), nullable=False),
        sa.Column("primary_diagnosis", sa.String(length=512), nullable=True),
        sa.Column("diagnosis_codes", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("follow_up_window_days", sa.Integer(), nullable=True),
        sa.Column("follow_up_deadline", sa.Date(), nullable=True),
        sa.Column("recommended_specialist", sa.String(length=128), nullable=True),
        sa.Column("urgent_flags", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column(
            "urgency_tier",
            sa.Enum("critical", "high", "medium", "routine", name="urgency_tier"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "patient_contacted",
                "scheduled",
                "seen",
                "confirmation_sent",
                "at_risk",
                name="discharge_status",
            ),
            nullable=False,
        ),
        sa.Column("confirmation_fax_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["referring_provider_id"], ["providers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discharge_summaries_clinic_id"), "discharge_summaries", ["clinic_id"], unique=False
    )
    op.create_index(
        op.f("ix_discharge_summaries_patient_id"),
        "discharge_summaries",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "eligibility_checks",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("insurance_policy_id", sa.UUID(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "result",
            sa.Enum("eligible", "ineligible", "pending", "error", name="eligibility_result"),
            nullable=False,
        ),
        sa.Column(
            "raw_response",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["insurance_policy_id"], ["insurance_policies.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eligibility_checks_clinic_id"), "eligibility_checks", ["clinic_id"], unique=False
    )
    op.create_index(
        op.f("ix_eligibility_checks_patient_id"), "eligibility_checks", ["patient_id"], unique=False
    )
    op.create_table(
        "faxes",
        sa.Column(
            "direction", sa.Enum("inbound", "outbound", name="fax_direction"), nullable=False
        ),
        sa.Column("patient_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column(
            "fax_type",
            sa.Enum(
                "referral", "discharge", "confirmation", "auth_packet", "other", name="fax_type"
            ),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=True),
        sa.Column("recipient_fax_number", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum("generated", "sending", "sent", "failed", name="fax_status"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_faxes_clinic_id"), "faxes", ["clinic_id"], unique=False)
    op.create_table(
        "referrals",
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("referring_provider_id", sa.UUID(), nullable=True),
        sa.Column("assigned_provider_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "needs_review",
                "missing_info",
                "ready_to_schedule",
                "auth_needed",
                "scheduled",
                "completed",
                "at_risk",
                "cancelled",
                name="referral_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "urgency",
            sa.Enum("stat", "urgent", "routine", "unclassified", name="urgency_level"),
            nullable=False,
        ),
        sa.Column("diagnosis_codes", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("procedure_codes", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("follow_up_window_days", sa.Integer(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_provider_id"], ["providers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["referring_provider_id"], ["providers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrals_clinic_id"), "referrals", ["clinic_id"], unique=False)
    op.create_index(op.f("ix_referrals_patient_id"), "referrals", ["patient_id"], unique=False)
    op.create_index(op.f("ix_referrals_status"), "referrals", ["status"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("referral_id", sa.UUID(), nullable=True),
        sa.Column("discharge_summary_id", sa.UUID(), nullable=True),
        sa.Column("appointment_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("appointment_type", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "confirmed",
                "completed",
                "no_show",
                "cancelled",
                "rescheduled",
                name="appointment_status",
            ),
            nullable=False,
        ),
        sa.Column("human_approved_by", sa.UUID(), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["discharge_summary_id"], ["discharge_summaries.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["human_approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["referral_id"], ["referrals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_appointments_appointment_at"), "appointments", ["appointment_at"], unique=False
    )
    op.create_index(op.f("ix_appointments_clinic_id"), "appointments", ["clinic_id"], unique=False)
    op.create_index(
        op.f("ix_appointments_patient_id"), "appointments", ["patient_id"], unique=False
    )
    op.create_table(
        "document_extractions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("extraction_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("field_confidences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("missing_fields", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column(
            "human_edits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("human_review_required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("human_reviewed_by", sa.UUID(), nullable=True),
        sa.Column("human_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_invocation_id", sa.UUID(), nullable=True),
        sa.Column("extraction_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ai_invocation_id"], ["ai_invocations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["human_reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_extractions_clinic_id"),
        "document_extractions",
        ["clinic_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_extractions_document_id"),
        "document_extractions",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "outreach_attempts",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("referral_id", sa.UUID(), nullable=True),
        sa.Column("discharge_summary_id", sa.UUID(), nullable=True),
        sa.Column(
            "channel", sa.Enum("sms", "email", "voice", name="outreach_channel"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "delivered",
                "responded",
                "no_response",
                "failed",
                name="outreach_status",
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "outcome", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("scheduling_link_url", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["discharge_summary_id"], ["discharge_summaries.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referral_id"], ["referrals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outreach_attempts_clinic_id"), "outreach_attempts", ["clinic_id"], unique=False
    )
    op.create_index(
        op.f("ix_outreach_attempts_patient_id"), "outreach_attempts", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_outreach_attempts_scheduled_at"),
        "outreach_attempts",
        ["scheduled_at"],
        unique=False,
    )
    op.create_table(
        "prior_auths",
        sa.Column("referral_id", sa.UUID(), nullable=True),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("payer_name", sa.String(length=128), nullable=False),
        sa.Column("payer_id", sa.String(length=64), nullable=True),
        sa.Column("member_id", app.utils.encryption.EncryptedString(), nullable=True),
        sa.Column("procedure_codes", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("diagnosis_codes", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column("auth_required", sa.Boolean(), nullable=True),
        sa.Column("auth_required_reasoning", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "not_needed",
                "checking",
                "required",
                "submitted",
                "approved",
                "denied",
                "appealing",
                "appeal_approved",
                "appeal_denied",
                name="prior_auth_status",
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("denied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auth_number", sa.String(length=128), nullable=True),
        sa.Column("packet_file_path", sa.String(length=1024), nullable=True),
        sa.Column("follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["referral_id"], ["referrals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prior_auths_clinic_id"), "prior_auths", ["clinic_id"], unique=False)
    op.create_index(op.f("ix_prior_auths_status"), "prior_auths", ["status"], unique=False)
    op.create_table(
        "referral_tasks",
        sa.Column("referral_id", sa.UUID(), nullable=True),
        sa.Column("discharge_summary_id", sa.UUID(), nullable=True),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "call_patient",
                "request_missing_info",
                "verify_eligibility",
                "submit_prior_auth",
                "schedule_appointment",
                "send_confirmation",
                "follow_up",
                "other",
                name="task_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "in_progress", "completed", "cancelled", "overdue", name="task_status"
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.UUID(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("critical", "high", "medium", "low", name="task_priority"),
            nullable=False,
        ),
        sa.Column("sla_hours", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["completed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["discharge_summary_id"], ["discharge_summaries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["referral_id"], ["referrals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referral_tasks_clinic_id"), "referral_tasks", ["clinic_id"], unique=False
    )
    op.create_index(op.f("ix_referral_tasks_due_at"), "referral_tasks", ["due_at"], unique=False)
    op.create_index(op.f("ix_referral_tasks_status"), "referral_tasks", ["status"], unique=False)
    op.create_table(
        "calls",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("outreach_attempt_id", sa.UUID(), nullable=True),
        sa.Column(
            "call_type",
            sa.Enum("outbound_scheduling", "outbound_followup", "inbound", name="call_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "initiated",
                "in_progress",
                "completed",
                "failed",
                "no_answer",
                "voicemail",
                name="call_status",
            ),
            nullable=False,
        ),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "outcome", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["outreach_attempt_id"], ["outreach_attempts.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["patient_id"], ["patients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calls_clinic_id"), "calls", ["clinic_id"], unique=False)
    op.create_index(op.f("ix_calls_patient_id"), "calls", ["patient_id"], unique=False)
    op.create_table(
        "prior_auth_events",
        sa.Column("prior_auth_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "submitted",
                "approved",
                "denied",
                "appeal_submitted",
                "appeal_approved",
                "appeal_denied",
                "follow_up_scheduled",
                "follow_up_completed",
                name="prior_auth_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["prior_auth_id"], ["prior_auths.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prior_auth_events_clinic_id"), "prior_auth_events", ["clinic_id"], unique=False
    )
    op.create_index(
        op.f("ix_prior_auth_events_prior_auth_id"),
        "prior_auth_events",
        ["prior_auth_id"],
        unique=False,
    )
    op.create_table(
        "call_transcripts",
        sa.Column("call_id", sa.UUID(), nullable=False),
        sa.Column("full_transcript", sa.Text(), nullable=False),
        sa.Column(
            "structured_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clinic_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["clinic_id"], ["clinics.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_call_transcripts_call_id"), "call_transcripts", ["call_id"], unique=False
    )
    op.create_index(
        op.f("ix_call_transcripts_clinic_id"), "call_transcripts", ["clinic_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_call_transcripts_clinic_id"), table_name="call_transcripts")
    op.drop_index(op.f("ix_call_transcripts_call_id"), table_name="call_transcripts")
    op.drop_table("call_transcripts")
    op.drop_index(op.f("ix_prior_auth_events_prior_auth_id"), table_name="prior_auth_events")
    op.drop_index(op.f("ix_prior_auth_events_clinic_id"), table_name="prior_auth_events")
    op.drop_table("prior_auth_events")
    op.drop_index(op.f("ix_calls_patient_id"), table_name="calls")
    op.drop_index(op.f("ix_calls_clinic_id"), table_name="calls")
    op.drop_table("calls")
    op.drop_index(op.f("ix_referral_tasks_status"), table_name="referral_tasks")
    op.drop_index(op.f("ix_referral_tasks_due_at"), table_name="referral_tasks")
    op.drop_index(op.f("ix_referral_tasks_clinic_id"), table_name="referral_tasks")
    op.drop_table("referral_tasks")
    op.drop_index(op.f("ix_prior_auths_status"), table_name="prior_auths")
    op.drop_index(op.f("ix_prior_auths_clinic_id"), table_name="prior_auths")
    op.drop_table("prior_auths")
    op.drop_index(op.f("ix_outreach_attempts_scheduled_at"), table_name="outreach_attempts")
    op.drop_index(op.f("ix_outreach_attempts_patient_id"), table_name="outreach_attempts")
    op.drop_index(op.f("ix_outreach_attempts_clinic_id"), table_name="outreach_attempts")
    op.drop_table("outreach_attempts")
    op.drop_index(op.f("ix_document_extractions_document_id"), table_name="document_extractions")
    op.drop_index(op.f("ix_document_extractions_clinic_id"), table_name="document_extractions")
    op.drop_table("document_extractions")
    op.drop_index(op.f("ix_appointments_patient_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_clinic_id"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_appointment_at"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_referrals_status"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_patient_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_clinic_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_faxes_clinic_id"), table_name="faxes")
    op.drop_table("faxes")
    op.drop_index(op.f("ix_eligibility_checks_patient_id"), table_name="eligibility_checks")
    op.drop_index(op.f("ix_eligibility_checks_clinic_id"), table_name="eligibility_checks")
    op.drop_table("eligibility_checks")
    op.drop_index(op.f("ix_discharge_summaries_patient_id"), table_name="discharge_summaries")
    op.drop_index(op.f("ix_discharge_summaries_clinic_id"), table_name="discharge_summaries")
    op.drop_table("discharge_summaries")
    op.drop_index(op.f("ix_ai_invocations_invocation_type"), table_name="ai_invocations")
    op.drop_index(op.f("ix_ai_invocations_clinic_id"), table_name="ai_invocations")
    op.drop_table("ai_invocations")
    op.drop_index(op.f("ix_insurance_policies_patient_id"), table_name="insurance_policies")
    op.drop_index(op.f("ix_insurance_policies_clinic_id"), table_name="insurance_policies")
    op.drop_table("insurance_policies")
    op.drop_index(op.f("ix_documents_clinic_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_workflow_runs_task_name"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_clinic_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_eval_runs_eval_type"), table_name="eval_runs")
    op.drop_index(op.f("ix_eval_runs_clinic_id"), table_name="eval_runs")
    op.drop_table("eval_runs")
    op.drop_index(op.f("ix_payer_rules_procedure_code"), table_name="payer_rules")
    op.drop_index(op.f("ix_payer_rules_payer_name"), table_name="payer_rules")
    op.drop_table("payer_rules")
    # ### end Alembic commands ###

    # Explicit enum drops — autogenerate omits these. ADR 004.
    for enum_name in _ENUMS_TO_DROP:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
